name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run: go mod tidy

      - name: Fetch required Go modules
        run: go mod download

      - name: Run Test
        run: |
          export CI=true
          make test

      - name: Build
        run: make build
